INSERT INTO chat.users(login, password) VALUES ('anna', '123456');
INSERT INTO chat.users(login, password) VALUES ('alsu', '752468');
INSERT INTO chat.users(login, password) VALUES ('maksim', '154789');
INSERT INTO chat.users(login, password) VALUES ('valery', '874598');
INSERT INTO chat.users(login, password) VALUES ('sokol', '882332');
INSERT INTO chat.users(login, password) VALUES ('vlad', '7768695');
INSERT INTO chat.users(login, password) VALUES ('aygul', '33412145');
INSERT INTO chat.users(login, password) VALUES ('stas', '6443645');
INSERT INTO chat.users(login, password) VALUES ('timur', '124621');
INSERT INTO chat.users(login, password) VALUES ('sanka', '123645');
INSERT INTO chat.users(login, password) VALUES ('vovik', '6427364');
INSERT INTO chat.users(login, password) VALUES ('smile', '2334662');
INSERT INTO chat.users(login, password) VALUES ('sliva', '7654663');
INSERT INTO chat.users(login, password) VALUES ('mimoza', '65542235');
INSERT INTO chat.users(login, password) VALUES ('anton', '6794333');
INSERT INTO chat.users(login, password) VALUES ('vanya', '634521');
INSERT INTO chat.users(login, password) VALUES ('lyuba', '9873214');
INSERT INTO chat.users(login, password) VALUES ('ramil', '8753523');
INSERT INTO chat.users(login, password) VALUES ('sila', '63125463');
INSERT INTO chat.users(login, password) VALUES ('likay', '8780786');
INSERT INTO chat.users(login, password) VALUES ('solovey', '324267');
INSERT INTO chat.users(login, password) VALUES ('luiza', '7532327');
INSERT INTO chat.room(name, owners) VALUES ('room_1', (SELECT id FROM chat.users WHERE id = 1));
INSERT INTO chat.room(name, owners) VALUES ('room_2', (SELECT id FROM chat.users WHERE id = 2));
INSERT INTO chat.room(name, owners) VALUES ('room_3', (SELECT id FROM chat.users WHERE id = 3));
INSERT INTO chat.room(name, owners) VALUES ('room_4', (SELECT id FROM chat.users WHERE id = 4));
INSERT INTO chat.room(name, owners) VALUES ('room_5', (SELECT id FROM chat.users WHERE id = 5));
INSERT INTO chat.room(name, owners) VALUES ('room_6', (SELECT id FROM chat.users WHERE id = 6));
INSERT INTO chat.room(name, owners) VALUES ('room_7', (SELECT id FROM chat.users WHERE id = 7));
INSERT INTO chat.room(name, owners) VALUES ('room_8', (SELECT id FROM chat.users WHERE id = 8));
INSERT INTO chat.room(name, owners) VALUES ('room_9', (SELECT id FROM chat.users WHERE id = 9));
INSERT INTO chat.room(name, owners) VALUES ('room_10', (SELECT id FROM chat.users WHERE id = 10));
INSERT INTO chat.room(name, owners) VALUES ('room_11', (SELECT id FROM chat.users WHERE id = 11));
INSERT INTO chat.room(name, owners) VALUES ('room_12', (SELECT id FROM chat.users WHERE id = 11));
INSERT INTO chat.room(name, owners) VALUES ('room_13', (SELECT id FROM chat.users WHERE id = 12));
INSERT INTO chat.room(name, owners) VALUES ('room_14', (SELECT id FROM chat.users WHERE id = 13));
INSERT INTO chat.room(name, owners) VALUES ('room_15', (SELECT id FROM chat.users WHERE id = 13));
INSERT INTO chat.room(name, owners) VALUES ('room_16', (SELECT id FROM chat.users WHERE id = 14));
INSERT INTO chat.room(name, owners) VALUES ('room_17', (SELECT id FROM chat.users WHERE id = 15));
INSERT INTO chat.room(name, owners) VALUES ('room_18', (SELECT id FROM chat.users WHERE id = 16));
INSERT INTO chat.room(name, owners) VALUES ('room_19', (SELECT id FROM chat.users WHERE id = 17));
INSERT INTO chat.room(name, owners) VALUES ('room_20', (SELECT id FROM chat.users WHERE id = 18));
INSERT INTO chat.room(name, owners) VALUES ('room_21', (SELECT id FROM chat.users WHERE id = 19));
INSERT INTO chat.room(name, owners) VALUES ('room_22', (SELECT id FROM chat.users WHERE id = 20));
INSERT INTO chat.room(name, owners) VALUES ('room_23', (SELECT id FROM chat.users WHERE id = 21));
INSERT INTO chat.room(name, owners) VALUES ('room_24', (SELECT id FROM chat.users WHERE id = 22));
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 1), (SELECT id FROM chat.room WHERE id = 1), 'Hi! Alsu');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 2), (SELECT id FROM chat.room WHERE id = 1), 'Im glad to see you! Anna');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 1), (SELECT id FROM chat.room WHERE id = 1), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 2), (SELECT id FROM chat.room WHERE id = 1), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 1), (SELECT id FROM chat.room WHERE id = 1), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 4), (SELECT id FROM chat.room WHERE id = 2), 'Hi! Maksim');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 3), (SELECT id FROM chat.room WHERE id = 2), 'Im glad to see you! valery');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 4), (SELECT id FROM chat.room WHERE id = 2), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 3), (SELECT id FROM chat.room WHERE id = 2), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 4), (SELECT id FROM chat.room WHERE id = 2), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 6), (SELECT id FROM chat.room WHERE id = 3), 'Hi! sokol');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 5), (SELECT id FROM chat.room WHERE id = 3), 'Im glad to see you! Vlad');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 6), (SELECT id FROM chat.room WHERE id = 3), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 5), (SELECT id FROM chat.room WHERE id = 3), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 6), (SELECT id FROM chat.room WHERE id = 3), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 8), (SELECT id FROM chat.room WHERE id = 4), 'Hi! Aygul');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 7), (SELECT id FROM chat.room WHERE id = 4), 'Im glad to see you! Stas');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 8), (SELECT id FROM chat.room WHERE id = 4), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 7), (SELECT id FROM chat.room WHERE id = 4), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 8), (SELECT id FROM chat.room WHERE id = 4), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 10), (SELECT id FROM chat.room WHERE id = 5), 'Hi! Sanka');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 9), (SELECT id FROM chat.room WHERE id = 5), 'Im glad to see you! Timur');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 10), (SELECT id FROM chat.room WHERE id = 5), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 9), (SELECT id FROM chat.room WHERE id = 5), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 10), (SELECT id FROM chat.room WHERE id = 5), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 11), (SELECT id FROM chat.room WHERE id = 6), 'Hi! Smile');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 12), (SELECT id FROM chat.room WHERE id = 6), 'Im glad to see you! Vovik');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 11), (SELECT id FROM chat.room WHERE id = 6), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 12), (SELECT id FROM chat.room WHERE id = 6), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 11), (SELECT id FROM chat.room WHERE id = 6), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 13), (SELECT id FROM chat.room WHERE id = 7), 'Hi! Mimoza');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 14), (SELECT id FROM chat.room WHERE id = 7), 'Im glad to see you! Sliva');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 13), (SELECT id FROM chat.room WHERE id = 7), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 14), (SELECT id FROM chat.room WHERE id = 7), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 13), (SELECT id FROM chat.room WHERE id = 7), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 15), (SELECT id FROM chat.room WHERE id = 8), 'Hi! Vanya');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 16), (SELECT id FROM chat.room WHERE id = 8), 'Im glad to see you! Anton');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 15), (SELECT id FROM chat.room WHERE id = 8), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 16), (SELECT id FROM chat.room WHERE id = 8), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 15), (SELECT id FROM chat.room WHERE id = 8), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 17), (SELECT id FROM chat.room WHERE id = 9), 'Hi! Ramil');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 18), (SELECT id FROM chat.room WHERE id = 9), 'Im glad to see you! Lyuba');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 17), (SELECT id FROM chat.room WHERE id = 9), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 18), (SELECT id FROM chat.room WHERE id = 9), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 17), (SELECT id FROM chat.room WHERE id = 9), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 19), (SELECT id FROM chat.room WHERE id = 10), 'Hi! Likay');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 20), (SELECT id FROM chat.room WHERE id = 10), 'Im glad to see you! Sila');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 19), (SELECT id FROM chat.room WHERE id = 10), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 20), (SELECT id FROM chat.room WHERE id = 10), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 19), (SELECT id FROM chat.room WHERE id = 10), 'How are you? Are you online now?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 21), (SELECT id FROM chat.room WHERE id = 11), 'Hi! Luiza');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 22), (SELECT id FROM chat.room WHERE id = 11), 'Im glad to see you! Solovey');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 21), (SELECT id FROM chat.room WHERE id = 11), 'How are you?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 22), (SELECT id FROM chat.room WHERE id = 11), 'Can I see you today?');
INSERT INTO chat.message(author, room, text) VALUES ((SELECT id FROM chat.users WHERE id = 21), (SELECT id FROM chat.room WHERE id = 11), 'How are you? Are you online now?');